format_version: 4
pipelines:
  outsystems-demo:
    group: outsystems
    label_template: "${git[:8]}"
    materials:
      git: 
        type: git
        url: https://github.com/OutSystems/outsystems-pipeline.git
        branch: github_actions
    parameters:
      param1: value1
    stages:
      - test:
          jobs:
            test:
              tasks:
                - script: |
                    echo ${param1}