format_version: 3
pipelines:
  - name: example-pipeline
    label_template: '${COUNT}'
    materials:
      - git: https://github.com/OutSystems/outsystems-pipeline.git
        branch: github_actions
    stages:
      - name: build
        jobs:
          - name: echo-job
            tasks:
              - script:
                  - echo "Hello, world!"
