format_version: 4
pipelines:
  outsystems-demo:
    group: outsystems
    label_template: "${git[:8]}"
    materials:
      outsystemsgit:
        git: https://github.com/OutSystems/outsystems-pipeline.git
        branch: github_actions
    stages:
      - test:
          jobs:
            test:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - echo hello