format_version: 4
pipelines:
  outsystems-demo:
    group: outsystems
    label_template: "${git[:8]}"
    materials:
      git: 
        type: git
        url: https://github.com/OutSystems/outsystems-pipeline.git
        branch: github_actions
    parameters:
      lifetime_hostname: showcase-lt.outsystemsdevopsexperts.com
      lifetime_api_version: 2
      development_env_label: DEV
      regression_env_label: REG
      acceptance_env_label: ACC
      preprod_env_label: PRE
      production_env_label: PRD
      os_package_version: 0.5.0
    secure_variables:
      lifetime_token: ${lifetime_token}
    environment_variables:
      manifest: Manifest in JSON format
    stages:
      - test:
          jobs:
            test:
#              inputs:
#                - manifest
              tasks:
                - script: |
                    echo "lifetime_hostname param value: #{lifetime_hostname}"
                - script: |
                    echo "Manifest (env) input value: %manifest%"
                - script: |
                    echo "lifetime_token (secret) value: %lifetime_token%"