format_version: 4
pipelines:
  outsystems-demo:
    group: outsystems
    label_template: "${git[:8]}"
    materials:
      git: 
        type: git
        url: https://github.com/OutSystems/outsystems-pipeline.git
        branch: github_actions
    parameters:
      - manifest
    stages:
      - test:
          jobs:
            test:
              inputs:
                - manifest
              tasks:
                - script: |
                    echo "Manifest input value: ${manifest}"