format_version: 4
pipelines:
  outsystems-demo:
    group: outsystems
    label_template: "${git[:8]}"
    materials:
      git: https://github.com/OutSystems/outsystems-pipeline
      branch: github_actions
    stages:
      - test:
          jobs:
            test:
              tasks:
                - script:
                    - echo "Hello World"