format_version: 4
pipelines:
  outsystems-demo:
    group: outsystems
    label_template: "${git[:8]}"
    materials:
      git: 
        type: git
        url: https://github.com/OutSystems/outsystems-pipeline.git
        branch: github_actions
    parameters:
      manifest: someValue
    environment_variables:
      my_manifest: testing
    stages:
      - test:
          jobs:
            test:
              inputs:
                - manifest
              tasks:
                - script: |
                    echo "Manifest (param) input value: #{manifest}"
                - script: |
                    echo "Manifest (env) input value: %my_manifest%"